import { Analytics as VercelAnalytics } from "@vercel/analytics/react";
import { FontAccent, FontSans } from "./fonts";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${FontSans.variable} ${FontAccent.variable}`}>
      <body>
        {children}
        <VercelAnalytics />
      </body>
    </html>
  );
}
