import { Providers } from "@/providers";
import { Analytics as VercelAnalytics } from "@vercel/analytics/react";
import { fonts } from "./fonts";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={fonts}
      data-theme="light"
      suppressHydrationWarning
    >
      <body>
        <Providers>{children}</Providers>
        <VercelAnalytics />
      </body>
    </html>
  );
}
